# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - front-react

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://thien.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_00ea2cf924d54753b50f9f9692713ee3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_dcefffd37d5b48ab990adfc1006a4703 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: thien.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_00ea2cf924d54753b50f9f9692713ee3 }}/react:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'front-react'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f092aa7cb9fc477aba07390ca913be62 }}
        images: 'thien.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_00ea2cf924d54753b50f9f9692713ee3 }}/react:${{ github.sha }}'